### ISSUE TITLE
Under which license is this library provided?

### ISSUE THREAD

**Issue by mirkojahn** [benbertola/metrics-watcher#8]
Hello, I tried to find information regarding the license under which the library could be used, but failed unfortunately.  Could you please provide a short statement regarding this? Without a proper license statement (ideally in the source) it is impossible to reuse (opensource wise and commercially). My preference, if I may add, would be a none viral license like ASL2 or BSD, of course. 

Thanks,
Mirko

**Comment by Webreaper** [comment]
Hi,

Would you be able to select a licence in github so there's an official licence against this repo? I'm investigating using this, but can't really use it unless there's an explicit licence specified that we can track back to. 

Thanks.

**Comment by benbertola** [comment]
I have now added the ASL2 license to the project, thank you everyone for your input on this.

**Comment by Webreaper** [comment]
Awesome, thanks for the quick response!
